version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - apt-get update
      - apt-get install -y unzip
  pre_build:
    commands:
      - npm install --legacy-peer-deps
  build:
    commands:
      - npm run build
      - zip -r build.zip build/
      - aws s3 cp build.zip s3://microfrontend-irm/subscriber/build.zip
  post_build:
    commands:
      - jar xf build.zip
      - aws s3 sync build/ s3://irm-mfe-subscriber/ --acl public-read

artificats:
  - "build/*"
