version: 2.1

executors:
  node-executor:
    docker:
      - image: node:18

jobs:
  notify:
    executor: node-executor
    steps:
      - run:
          name: Install Prerequisites
          command: |
            apt-get update
            apt-get install -y jq

      - run:
          name: Notify RingCentral
          command: |
            curl --location --request POST 'https://hooks.ringcentral.com/webhook/v2/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvdCI6ImMiLCJvaSI6IjE0MjkyMDkwODkiLCJpZCI6IjI4MDk1NjkzMDcifQ.-WyR3x9Z_s0YYvmeB39uTLpTu0eWQYO9iSU-xu1U50Q' \
            --header 'Content-Type: application/json' \
            --data "$(jq -n --arg activity "Microfrontend New Deployment Notification" \
                      --arg title "Visp ${CIRCLE_TAG} client: released to App" \
                      --arg body "[changelog/updates](https://github.com/VISPdevteam/Tickets-Micro-Frontend/releases/tag/${CIRCLE_TAG})" \
                      --arg icon "https://yt3.ggpht.com/a/AGF-l7_s7iCi6dgwawf4rkbIMwUo6WpZLkYw0k9h4w=s100-c-k-c0xffffffff-no-rj-mo" \
                      --argjson build_num ${CIRCLE_BUILD_NUM} \
                      --arg build url "${CIRCLE_BUILD_URL}" \
                      '{payload: {activity: $activity, title: $title, body: $body, icon: $icon, build_num: $build_num}}')"

workflows:
  notify_workflow:
    jobs:
      - notify
