version: 2.1

executors:
  node-executor:
    docker:
      - image: node:18

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --legacy-peer-deps
      - run:
          name: Build the application
          command: npm run build
      - run:
          name: Verify Build Artifacts
          command: ls -la build/
      - run:
          name: Create Dist folder and copy build artifacts
          command: mkdir dist && cp -r build/* dist/
      - run:
          name: Install zip utility
          command: |
            apt-get update
            apt-get install -y zip
      - run:
          name: Zip the build artifacts
          command: zip -r build.zip dist
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run:
          name: Verify Workspace Contents
          command: ls -la /workspace/dist
      - run:
          name: Install Prerequisites
          command: apt-get update && apt-get install -y unzip less
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region $AWS_REGION
      - run:
          name: Upload to S3
          command: |
            BRANCH_NAME=prod
            S3_BUCKET=microfrontend-crm-ms
            aws s3 sync /workspace/dist/ s3://$S3_BUCKET/$BRANCH_NAME/ --acl public-read
      - run:
          name: Verify S3 Upload
          command: aws s3 ls s3://$S3_BUCKET/$BRANCH_NAME/
      - run:
          name: Invalidate CloudFront Cache
          command: |
            CLOUDFRONT_DIST_ID=E27YPOVXTAAHKM
            BRANCH_NAME=prod
            aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"
            DEPLOY_URL="https://crm-microfrontend.ms-visp.net/$BRANCH_NAME"
            echo "Microfrontend is accessible at: $DEPLOY_URL"
      - run:
          name: Check CloudFront Invalidations
          command: aws cloudfront list-invalidations --distribution-id $CLOUDFRONT_DIST_ID
      - run:
          name: Notify RingCentral
          command: |
            curl --location --request POST 'https://hooks.ringcentral.com/webhook/v2/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvdCI6ImMiLCJvaSI6IjE0MjkyMDkwODkiLCJpZCI6IjI4MDk1NjkzMDcifQ.-WyR3x9Z_s0YYvmeB39uTLpTu0eWQYO9iSU-xu1U50Q' \
            --header 'Content-Type: application/json' \
            --data '{
              "payload": {
                "activity": "Microfrontend New Deployment Notification",
                "title": "Visp ${CIRCLE_TAG} client: released to App",
                "body": "[changelog/updates](https://github.com/VISPdevteam/Tickets-Micro-Frontend/releases/tag/${CIRCLE_TAG})",
                "status": "success",
                "build_num": '${CIRCLE_BUILD_NUM}',
                "branch": "${CIRCLE_BRANCH}",
                "reponame": "${CIRCLE_PROJECT_REPONAME}",
                "username": "${CIRCLE_USERNAME}",
                "build_url": "https://circleci.com/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BUILD_NUM}",
                "vcs_url": "https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
              }
            }'

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
